name: Deploy Quartz site to GitHub Pages and Public Folder

on:
  push:
    branches:
      - v4

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for committing to the branch

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

#      - name: Build Quartz
#        run: |
#          npx quartz build --serve &
#          QUARTZ_PID=$!          
#          echo "Waiting for Quartz build to finish..."
#          sleep 15          
#          echo "Killing Quartz server..."
#          kill $QUARTZ_PID || echo "Quartz server already stopped"
    
      - name: Build Quartz
        run: npx quartz build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Commit and Push Public Folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public
          git commit -m "Update public folder after build [skip ci]" || echo "No changes to commit"
          git push origin v4
